version: '3'
services:
  database:
    image: postgres:9.6
    container_name: daily-diet-db
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - daily-diet

  api:
    image: daily-diet-api:v1
    build: .
    container_name: daily-diet-api
    # command: prisma migrate resolve --rolled-back "20231114161725_create_table"
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - daily-diet
    depends_on:
    - database

networks:
  daily-diet:
    driver: bridge
    